-- ============================================================
-- V1__initial_schema.sql
-- Πλήρες αρχικό σχήμα. Αντικαθιστά το ddl-auto: update (D23).
-- Σειρά δημιουργίας = σειρά εξάρτησης FK: ένας πίνακας
-- δημιουργείται ΜΟΝΟ αφού υπάρχουν όσοι τον προηγούνται.
-- ============================================================

-- ---- business_settings (singleton, D39) ----
-- id ΧΩΡΙΣ auto-generate: ο κανόνας "ένα μαγαζί" ζει στο PK (id=1 πάντα).
CREATE TABLE business_settings (
                                   id                       BIGINT       PRIMARY KEY,   -- όχι GENERATED: singleton (D39)
                                   name                     VARCHAR(255) NOT NULL,
                                   type                     VARCHAR(50)  NOT NULL,       -- BusinessType enum ως STRING (D21)
                                   address                  VARCHAR(255),
                                   phone                    VARCHAR(50),
                                   email                    VARCHAR(255),
                                   timezone                 VARCHAR(100) NOT NULL,       -- IANA String, π.χ. "Europe/Athens" (D35)
                                   slot_granularity_minutes INTEGER      NOT NULL,       -- επιχειρησιακή ρύθμιση (D15)
                                   booking_lead_time_minutes INTEGER     NOT NULL,       -- D68, default 10 μπαίνει στο seed
                                   setup_completed          BOOLEAN      NOT NULL
);

-- ---- users ----
-- BIGINT GENERATED ... AS IDENTITY = το PostgreSQL αντίστοιχο του @GeneratedValue(IDENTITY).
-- Το Long (wrapper) στην Java: null = transient (D24).
CREATE TABLE users (
                       id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email         VARCHAR(255) NOT NULL UNIQUE,           -- login identifier (D54)
                       password_hash VARCHAR(255) NOT NULL,                  -- BCrypt hash, ποτέ plaintext
                       full_name     VARCHAR(255) NOT NULL,
                       phone         VARCHAR(50),
                       active        BOOLEAN      NOT NULL,                   -- μπορεί να κάνει login; (D36)
                       created_at    TIMESTAMPTZ  NOT NULL,                  -- Instant → timestamptz (D4)
                       updated_at    TIMESTAMPTZ
);

-- ---- user_roles (D9: Set<Role>, @ElementCollection) ----
-- Πολλαπλοί ρόλοι ανά χρήστη (ADMIN+EMPLOYEE εφικτό, D8). Σύνθετο PK
-- (user_id, role) = κάθε ρόλος το πολύ μία φορά ανά χρήστη.
CREATE TABLE user_roles (
                            user_id BIGINT      NOT NULL REFERENCES users(id),
                            role    VARCHAR(20) NOT NULL,                       -- Role enum ΧΩΡΙΣ ROLE_ prefix (D53)
                            PRIMARY KEY (user_id, role)
);
-- ---- service_categories ----
CREATE TABLE service_categories (
                                    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    name          VARCHAR(255) NOT NULL UNIQUE,
                                    display_order INTEGER      NOT NULL,                   -- σειρά εμφάνισης (D43)
                                    active        BOOLEAN      NOT NULL
);

-- ---- employee_profiles (D8: User + EmployeeProfile composition) ----
-- Ο υπάλληλος ΔΕΝ είναι ξεχωριστός τύπος χρήστη· είναι ένας User ΜΕ profile.
-- Γι' αυτό FK προς users, ΟΧΙ inheritance. user_id UNIQUE = ένα profile ανά χρήστη.
CREATE TABLE employee_profiles (
                                   id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   user_id   BIGINT       NOT NULL UNIQUE REFERENCES users(id),  -- 1:1 προς User
                                   bio       VARCHAR(1000),
                                   photo_url VARCHAR(500),
                                   active    BOOLEAN      NOT NULL                     -- εμφανίζεται στην κράτηση; (D36)
);

-- ---- services (κλάση ServiceOffering, πίνακας services — D25) ----
CREATE TABLE services (
                          id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          category_id      BIGINT        NOT NULL REFERENCES service_categories(id),
                          name             VARCHAR(255)  NOT NULL,
                          description      VARCHAR(1000),
                          duration_minutes INTEGER       NOT NULL,            -- ακέραια λεπτά, μονάδα στο όνομα (D33)
                          price            NUMERIC(8,2)  NOT NULL,            -- BigDecimal precision=8 scale=2 (D29)
                          target_audience  VARCHAR(20)   NOT NULL,            -- TargetAudience enum ως STRING (D21)
                          active           BOOLEAN       NOT NULL
);

-- ---- employee_services (D30: @ManyToMany, join table) ----
-- Ποιος υπάλληλος προσφέρει ποια υπηρεσία. Σύνθετο PK (και τα δύο FKs μαζί) =
-- κάθε ζεύγος (employee, service) το πολύ μία φορά. Κανένα cascade (D30).
CREATE TABLE employee_services (
                                   employee_id BIGINT NOT NULL REFERENCES employee_profiles(id),
                                   service_id  BIGINT NOT NULL REFERENCES services(id),
                                   PRIMARY KEY (employee_id, service_id)               -- composite PK
);

-- ---- working_hours (D34: πολλές γραμμές/μέρα = βάρδιες) ----
-- FK προς employee_profiles, ΟΧΙ users (ασυμμετρία — δες PROJECT.md section 6).
-- day_of_week + start/end = ΚΑΝΟΝΑΣ χωρίς ημερομηνία → LocalTime/DayOfWeek (D4).
CREATE TABLE working_hours (
                               id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               employee_id BIGINT      NOT NULL REFERENCES employee_profiles(id),
                               day_of_week VARCHAR(20) NOT NULL,                   -- DayOfWeek enum ως STRING (D21)
                               start_time  TIME        NOT NULL,                   -- LocalTime → TIME (ΟΧΙ timestamptz!)
                               end_time    TIME        NOT NULL
);

-- ---- time_off (άδεια = ΓΕΓΟΝΟΣ, όχι κανόνας → Instant, D4) ----
CREATE TABLE time_off (
                          id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          employee_id BIGINT       NOT NULL REFERENCES employee_profiles(id),
                          starts_at   TIMESTAMPTZ  NOT NULL,                  -- συγκεκριμένη στιγμή → timestamptz
                          ends_at     TIMESTAMPTZ  NOT NULL,
                          reason      VARCHAR(500)
);

-- ---- appointments ----
-- ΑΣΥΜΜΕΤΡΙΑ FK (κρίσιμο, PROJECT.md section 6):
--   customer_id → users            (ο πελάτης είναι απλός χρήστης)
--   employee_id → employee_profiles (ο υπάλληλος είναι ρόλος με profile, D8)
-- starts_at/ends_at ΚΑΙ ΤΑ ΔΥΟ αποθηκευμένα (D5): αν αλλάξει η διάρκεια
-- υπηρεσίας αργότερα, το ιστορικό ραντεβού ΔΕΝ αλλάζει αναδρομικά.
CREATE TABLE appointments (
                              id                     BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              customer_id            BIGINT       NOT NULL REFERENCES users(id),
                              employee_id            BIGINT       NOT NULL REFERENCES employee_profiles(id),
                              starts_at              TIMESTAMPTZ  NOT NULL,        -- Instant (D4)
                              ends_at                TIMESTAMPTZ  NOT NULL,
                              status                 VARCHAR(20)  NOT NULL,        -- AppointmentStatus enum ως STRING (D21)
                              total_price            NUMERIC(8,2) NOT NULL,        -- BigDecimal (D29)
                              total_duration_minutes INTEGER      NOT NULL,        -- effective duration (D16/D82)
                              created_at             TIMESTAMPTZ  NOT NULL,
                              cancelled_at           TIMESTAMPTZ,                  -- nullable: μόνο αν ακυρωθεί
                              cancellation_reason    VARCHAR(500)
);

-- ---- appointment_items (children του aggregate, D41) ----
-- SNAPSHOTS (D6): price_snapshot + duration_snapshot = φωτογραφία τη στιγμή
-- της κράτησης. Το FK προς services μένει για όνομα + στατιστικά, ΑΛΛΑ οι
-- τιμές/διάρκειες διαβάζονται από τα snapshots (temporal data).
-- ON DELETE CASCADE = όταν σβήνει το appointment, σβήνουν τα items του
-- (orphanRemoval + cascade=ALL στο aggregate root, D41).
CREATE TABLE appointment_items (
                                   id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   appointment_id   BIGINT       NOT NULL REFERENCES appointments(id) ON DELETE CASCADE,
                                   service_id       BIGINT       NOT NULL REFERENCES services(id),
                                   price_snapshot   NUMERIC(8,2) NOT NULL,             -- τιμή τη στιγμή κράτησης (D6)
                                   duration_snapshot INTEGER     NOT NULL,             -- πραγματική διάρκεια, ΟΧΙ effective (D82)
                                   sort_order       INTEGER      NOT NULL              -- σειρά υπηρεσιών (D43)
);

-- ---- reviews (D37: @OneToOne προς appointment) ----
-- appointment_id UNIQUE = δομικά αδύνατο να αξιολογήσεις 2 φορές το ίδιο
-- ραντεβού, ή ραντεβού που δεν σε εξυπηρέτησε ποτέ. Το FK ΕΙΝΑΙ ο κανόνας.
CREATE TABLE reviews (
                         id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         appointment_id BIGINT       NOT NULL UNIQUE REFERENCES appointments(id),
                         rating         INTEGER      NOT NULL,               -- CHECK 1-5 μπαίνει στο V2
                         comment        VARCHAR(1000),
                         created_at     TIMESTAMPTZ  NOT NULL
);