-- ═══════════════════════════════════════════════════════════════════════
-- V8 — Επιβράβευση ως «σφραγίδες + αποθηκευμένα δώρα» (D173)
--
-- Αλλάζει το ΠΩΣ μετράμε (derived D168 → ledger). ΜΕΝΟΥΝ ως έχουν από το V7:
--   - business_settings.loyalty_*            (ο τρέχων κανόνας: N, %, on/off)
--   - appointments.discount_percent/amount   (snapshot τιμής, D6)
--
-- ΚΑΜΙΑ συμπλήρωση παλιών δεδομένων: το DEFAULT FALSE δίνει σε ΟΛΑ τα
-- υπάρχοντα ραντεβού "χωρίς σφραγίδα" → όλοι ξεκινούν από 0 (D173 κανόνας 1).
-- ═══════════════════════════════════════════════════════════════════════


-- ── 1) Τα κερδισμένα δώρα: ΜΙΑ γραμμή ανά δώρο ────────────────────────
-- Κάθε δώρο κρατάει το % και το N που ίσχυαν τη στιγμή που κερδήθηκε
-- (D173 κανόνες 2 & 6) → αλλαγή ρυθμίσεων δεν το αγγίζει ποτέ.
CREATE TABLE loyalty_rewards (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      BIGINT      NOT NULL REFERENCES users (id),
    discount_percent INTEGER     NOT NULL,
    visits_required  INTEGER     NOT NULL,
    earned_at        TIMESTAMPTZ NOT NULL,

    -- Ίδια όρια με το business_settings (V7): ένα δώρο δεν μπορεί να
    -- «γεννηθεί» με τιμή που οι ρυθμίσεις δεν θα επέτρεπαν.
    CONSTRAINT loyalty_reward_percent_range CHECK (discount_percent BETWEEN 1 AND 100),
    CONSTRAINT loyalty_reward_visits_min    CHECK (visits_required >= 2),

    -- Στόχος του σύνθετου FK από το appointments (βλ. 4).
    -- Το id είναι ήδη μοναδικό, άρα και το ζεύγος· η PostgreSQL όμως απαιτεί
    -- ρητό UNIQUE στις ΑΚΡΙΒΕΙΣ στήλες στις οποίες δείχνει ένα FK.
    -- Σειρά (customer_id, id): το index που δημιουργείται ξεκινά από customer_id
    -- → εξυπηρετεί ΚΑΙ το «δώρα του πελάτη X» (η PostgreSQL δεν κάνει
    -- αυτόματα index σε στήλες FK) → δεν χρειάζεται δεύτερο index.
    CONSTRAINT loyalty_reward_customer_id_unique UNIQUE (customer_id, id)
);


-- ── 2) Νέες στήλες στα ραντεβού ────────────────────────────────────────
ALTER TABLE appointments
    -- Σφραγίδα = γεγονός που καταγράφεται τη στιγμή της ολοκλήρωσης
    -- (αν το πρόγραμμα ήταν ενεργό ΤΟΤΕ). Δεν υπολογίζεται εκ των υστέρων.
    ADD COLUMN loyalty_stamp     BOOLEAN NOT NULL DEFAULT FALSE,
    -- Ποιο δώρο «εξαργυρώνει» αυτό το ραντεβού (NULL = κανένα).
    ADD COLUMN loyalty_reward_id BIGINT;


-- ── 3) Κανόνες συνέπειας ανά γραμμή (D45: η βάση = τελευταίο δίχτυ) ────
ALTER TABLE appointments
    -- Σφραγίδα μόνο σε ολοκληρωμένο ραντεβού εγγεγραμμένου πελάτη
    -- (walk-in = χωρίς λογαριασμό = εκτός προγράμματος, D139).
    ADD CONSTRAINT loyalty_stamp_only_completed_customer
        CHECK (NOT loyalty_stamp
               OR (status = 'COMPLETED' AND customer_id IS NOT NULL)),

    -- Δεμένο δώρο ⇒ εγγεγραμμένος πελάτης ΚΑΙ έκπτωση στο snapshot.
    -- Μονόδρομο σκόπιμα: τα ραντεβού του Chat 16 έχουν έκπτωση ΧΩΡΙΣ δώρο
    -- (παλιό μοντέλο) και πρέπει να παραμείνουν έγκυρα ως ιστορικό.
    -- Το customer_id IS NOT NULL χρειάζεται ΚΑΙ για το FK του βήματος 4.
    ADD CONSTRAINT loyalty_reward_needs_customer_and_discount
        CHECK (loyalty_reward_id IS NULL
               OR (customer_id IS NOT NULL AND discount_percent > 0));


-- ── 4) Ένα ραντεβού εξαργυρώνει μόνο δώρο του ΙΔΙΟΥ πελάτη ─────────────
-- Σύνθετο FK: το ζεύγος (customer_id, loyalty_reward_id) πρέπει να υπάρχει
-- στο loyalty_rewards → δομικά αδύνατο να χρησιμοποιηθεί ξένο δώρο
-- (ίδια ιδέα με το D37: το FK αποκλείει την αδύνατη περίπτωση).
-- MATCH SIMPLE (default): αν ΟΠΟΙΑΔΗΠΟΤΕ στήλη είναι NULL, το FK δεν ελέγχεται.
--   loyalty_reward_id NULL → σωστά αγνοείται (ραντεβού χωρίς δώρο)
--   customer_id NULL με δώρο → θα ξέφευγε, αλλά το αποκλείει το CHECK του 3.
ALTER TABLE appointments
    ADD CONSTRAINT appointment_reward_same_customer
        FOREIGN KEY (customer_id, loyalty_reward_id)
        REFERENCES loyalty_rewards (customer_id, id);


-- ── 5) Ένα δώρο → το πολύ ΕΝΑ ενεργό ραντεβού (partial unique index) ────
-- Μοναδικότητα ΜΟΝΟ στις γραμμές που ικανοποιούν το WHERE:
--   - ακύρωση → το ραντεβού βγαίνει από το index → το δώρο ξαναγίνεται
--     ελεύθερο με ΜΗΔΕΝ κώδικα (D173 κανόνας 4)· το ακυρωμένο ραντεβού
--     κρατά το loyalty_reward_id ως ιστορικό.
--   - δύο ταυτόχρονες κρατήσεις με το ίδιο δώρο → η 2η παίρνει unique
--     violation → 409 (κλείνει το «γνωστό όριο» του D170).
-- Το IS NOT NULL είναι τυπικά περιττό (τα NULL δεν συγκρούονται σε UNIQUE),
-- αλλά κρατά το index μικρό: μπαίνουν μόνο ραντεβού με δώρο.
CREATE UNIQUE INDEX uq_loyalty_reward_single_use
    ON appointments (loyalty_reward_id)
    WHERE loyalty_reward_id IS NOT NULL AND status <> 'CANCELLED';
